# permissions for end users to view influxdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: influxdb-viewer-role
rules:
- apiGroups:
  - influxdb.influxdata.com
  resources:
  - influxdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - influxdb.influxdata.com
  resources:
  - influxdbs/status
  verbs:
  - get
