
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - influxdb.influxdata.com
  resources:
  - influxdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - influxdb.influxdata.com
  resources:
  - influxdbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - influxdb.influxdata.com
  resources:
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - influxdb.influxdata.com
  resources:
  - tokens/status
  verbs:
  - get
  - patch
  - update
