# permissions for end users to edit tokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: token-editor-role
rules:
- apiGroups:
  - influxdb.influxdata.com
  resources:
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - influxdb.influxdata.com
  resources:
  - tokens/status
  verbs:
  - get
